### ISSUE TITLE
搭建离线npm仓库遇到的问题

### ISSUE THREAD

**Issue by NemoZhong** [NemoZhong/blog-nemo#25]

**Comment by NemoZhong** [comment]
background:  在vdi纯内网环境搭建Npm仓库，使用`verdaccio`镜像直接启动仓库，项目中的包打算下载到仓库内存放包的地方

**Comment by NemoZhong** [comment]
😂刚开始以为直接把项目的package.json和lock文件拿出来install后，放在verdaccio仓库镜像里就好了，dockerfile将本地install的node_modules拷进/verdaccio/storage目录下，结果启起来始终找不到任何包。后面打开package-lock文件才注意到npm仓库实际上存放的是`.tgz`的压缩包。比如`dayjs`@1.11.9，在lock文件中是存在`https://registry.npmjs.org/dayjs/-/dayjs-1.11.9.tgz`下的。所以实际上应该把所有的`tgz`包放在容器的`/verdaccio/storage`目录下

**Comment by NemoZhong** [comment]
1. 全局安装tgz包下载工具 `node-tgz-downloader`
2. 将package-lock.json放在目录下，下载文件
```
npm install node-tgz-downloader -g

### package-lock.json可以是url
download-tgz package-lock package-lock.json
```
3. 得到的文件夹tarballs，目录结构就是实际上npm仓库存放包的结构

**Comment by NemoZhong** [comment]
然后直接把文件夹挂载在容器的/storage目录下，使用`docker-compose up -d`启动仓库镜像，即可
```
version: '3'
services:
  verdaccio:
    image: verdaccio/verdaccio
    ports:
      - "4873:4873"
    volumes:
      - ./tarballs:/verdaccio/storage
    restart: always
```
